# Generated by Django 5.2.4 on 2025-07-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgrid_api', '0002_audit_operator_signature_audit_supervisor_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('code_anomalie', models.CharField(max_length=50)),
                ('chapitre_mlp', models.CharField(max_length=50)),
            ],
        ),
    ]
