# Generated by Django 5.2.4 on 2025-07-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgrid_api', '0003_gridrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gridrow',
            old_name='label',
            new_name='anomalie',
        ),
        migrations.RemoveField(
            model_name='gridrow',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gridrow',
            name='chapitre_mlp',
        ),
        migrations.AddField(
            model_name='gridrow',
            name='aviexp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='bl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='chapitre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='info_sup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='uc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='um',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='ums',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gridrow',
            name='code_anomalie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
