# Generated by Django 5.2.4 on 2025-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgrid_api', '0004_rename_label_gridrow_anomalie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridrow',
            name='aviexp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='bl_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='uc_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='um_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gridrow',
            name='ums_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
