# Generated by Django 5.2.4 on 2025-07-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartgrid_api', '0005_gridrow_aviexp_enabled_gridrow_bl_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gridrow',
            old_name='aviexp_enabled',
            new_name='avexp_enabled',
        ),
        migrations.RenameField(
            model_name='gridrow',
            old_name='ums_enabled',
            new_name='ugs_enabled',
        ),
    ]
