# Generated by Django 5.2.4 on 2025-07-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgrid_api', '0006_rename_aviexp_enabled_gridrow_avexp_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='operator_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='supervisor_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
