# Generated by Django 5.2.4 on 2025-07-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgrid_api', '0007_alter_audit_operator_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformite',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nonconformite',
            name='chapitre_mlp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nonconformite',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
