# Generated by Django 5.2.4 on 2025-07-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgrid_api', '0008_alter_nonconformite_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='code_route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='cofor_audite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='el_bl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
