# Generated by Django 5.2.4 on 2025-07-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgrid_api', '0009_audit_code_route_audit_cofor_audite_audit_el_bl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(blank=True, choices=[('A', 'Shift A'), ('B', 'Shift B'), ('Night', 'Night')], max_length=10, null=True),
        ),
    ]
