# Generated by Django 5.2.4 on 2025-07-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgrid_api', '0010_user_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridrow',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
